### ISSUE TITLE
[BUG] Rath Filter Slider cannot move

### ISSUE THREAD

**Issue by ObservedObserver** [Kanaries/Rath#133]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/22167673/191542461-a02a842f-e35f-486d-8db9-144df6d213c0.png">

+ slider interaction bug
+ filter i18n

**Comment by AntoineYANG** [comment]
In this case RangeSelector component which includes a Slider failed to behaviour when it receives string values as props.

At the page of DataSource, users will interact while only RAW data visible to them, some fields which will be marked as quantitative, transformed from strings to numbers, is string instances at that time. Type check and safe parsing should be attached to make sure that string values will not be passed to the RangeSelector component.
