### ISSUE TITLE
Notebook Board is destroying the continuity of the algorithm!

### ISSUE THREAD

**Issue by ObservedObserver** [Kanaries/Rath#2]
Currently designed `notebook` breaks the continuity of the algorithm. The result of each steps of the algorithm has to be transport between front end and backend, which might be a potential cost of traffic and efficiency.

It also improve the cost for front end to maintain the state of the algorithm. It requires the front end to adjust the algorithm's output for next stage which make the computation logic separated maintained in different places.

Suggestions:
+ make the algorithm pipeline a more continuous process.
+ provide hooks to get the result from steps in the process with out breaking the process.

**Comment by guanxyz** [comment]
有没有兴趣来读硕士或者博士

**Comment by ObservedObserver** [comment]
> 有没有兴趣来读硕士或者博士

有兴趣呀，在哪里 :eyes:

**Comment by guanxyz** [comment]
USA Kent State
