### ISSUE TITLE
yarn workspace backend dev

### ISSUE THREAD

**Issue by avsilva** [Kanaries/Rath#27]
After installing all packages and dependencies, running yarn workspace backend dev
throws error:

Rath/node_modules/visual-insights/build/esm"' has no exported member 'getInsightViews'.

import { getInsightViews } from 'visual-insights';

**Comment by ObservedObserver** [comment]
Sorry, I forget to update the doc. Currently, the backend of Rath had been deprecated. All computation services are running in web workers, which means you only need to start the frontend parts of Rath.

**Comment by avsilva** [comment]
tks, great !!!
