### ISSUE TITLE
browser out of memory

### ISSUE THREAD

**Issue by yepengxj** [Kanaries/Rath#298]
Browser out of memory when connect to 100M rows and >100 columns  clickhouse table
Rath : latest
Egde browser: 110.0.1587
clickhouse: 22.11

**Comment by ObservedObserver** [comment]
It seems you are still using in-memory mode for large datasets.

For larger datasets than 100M, you need to switch to MPP mode, so RATH can put computation tasks into your OLAP engine.

**Comment by yepengxj** [comment]
Could open source Rath switch to mpp mode?
