### ISSUE TITLE
Runtime error: Cannot read property 'semanticType' of undefined

### ISSUE THREAD

**Issue by zhtangsh** [Kanaries/Rath#30]
Hi, there

I feed sample data to Rath with commit `a3511d2bd8e529a2e2502a5fc4a2cf65120c2e87`.
I could only get entropy info per column. When I clicked generate dashboard, I got this runtime error `Cannot read property 'semanticType' of undefined`

<img width="1680" alt="Screen Shot 2020-06-17 at 10 16 21 AM" src="https://user-images.githubusercontent.com/12687471/84847574-08ead200-b084-11ea-9986-01600a27c95e.png">
Any clues on this one?

**Comment by ObservedObserver** [comment]
#31 
> Issues: #30 .
> 
> It seems targetVis fails to handle the case when the field does not exist, which is possible because the recommended visual specification could provide encodings without color channel.
>
> The same case had been considered in featureVis, but forgotten in targetVis.
>
> However, normally, data views targetVis get should have at least one dimension(feature). And the auto specification has a high possibility of encoding the feature into color(perception error).
>
>I'm curious about what channel is used for the dimension if it is not color and why(depends on the dataset).
> or the dataset might do not contain any dimensions.

**Comment by ObservedObserver** [comment]
fixed in the latest commit(`61996c3db2d207860f460526bf6f16347e3215f2`).
