### ISSUE TITLE
Bug: Safari not support RegExp with `(?<=...)` yet which leads to blank webpage for Safari Users visiting RATH.

### ISSUE THREAD

**Issue by jojocys** [Kanaries/Rath#306]
Bug: Safari not support RegExp with `(?<=...)` yet which leads to blank webpage for Safari Users visiting RATH.

Message Link In Discord: https://discord.com/channels/987366424634884096/1057481447541325885/1076425723855773747

![image](https://user-images.githubusercontent.com/59559181/219923472-656f9cb9-1f48-45dc-80e9-c5960a54358f.png)

**Comment by ObservedObserver** [comment]
fixed in https://github.com/Kanaries/Rath/commit/4613d9ad974a7e113fcd9f390269df147c9316d9
