### ISSUE TITLE
Causal Analysis seems to not be functioning

### ISSUE THREAD

**Issue by i-love-mario** [Kanaries/Rath#365]
Hello team,

I read the document and clicked on the "Causal Discovery" button under "Causal Analysis", but the following message appeared:

> Causal Discovery Error
> Algorithm is not chosen yet.

Even when I checked the "Settings," there is no option to select an "Algorithm," only blank choices are available.
![image](https://github.com/Kanaries/Rath/assets/106466687/44dc1c65-c5e3-4a3d-853e-3f2bb9b0371a)

This project is an excellent project. Thank you.

**Comment by ObservedObserver** [comment]
Causal discovery is not provided in the playground. You can access it at the SaaS version at kanaries.net or using the open-source version deployed by yourself.

There are some services in the `services` folder in the repo, which you may need to start them based on your needs.
