### ISSUE TITLE
ChatGPT feature is missing from Rath

### ISSUE THREAD

**Issue by al-yakubovich** [Kanaries/Rath#369]
I have read this post
https://docs.kanaries.net/articles/chatgpt-prompts-data-visualization

and it has "Semi-auto Exploration" tab:
![image](https://github.com/Kanaries/Rath/assets/12928778/d26e5e0d-51e9-44df-882f-f68ab45fb88e)

I tried to run Rath locally but instead I see "Data Copilot":
![image](https://github.com/Kanaries/Rath/assets/12928778/4c17e462-e39e-4c80-af59-e76b6edd30a5)

So there is no ChatGPT feature here. Is it a bug or has it not been added yet? 

BTW, awesome framework!

**Comment by ObservedObserver** [comment]
We have not made that part open-source yet based on some engineering issues (it relays some internal services of kanaries). It will be opensource after we refactor it.

**Comment by nuaabuaa07** [comment]
I still can not find 'ask' button as show in  picture.Is 'nlp to graph' feature support now?
