### ISSUE TITLE
Remove default logging to third party

### ISSUE THREAD

**Issue by iasomiero** [Kanaries/Rath#375]
Remove all data logging to a third party url. 

const DATA_SOURCE_LOGGER_URL = 'https://1423108296428281.cn-hangzhou.fc.aliyuncs.com/2016-08-15/proxy/Rath/dataSourceLogger/'

This looks like data stealing and because of that this nice project will be flagged by any security tool as spyware.

**Comment by ObservedObserver** [comment]
done
