### ISSUE TITLE
Cannot parse title with "\n"

### ISSUE THREAD

**Issue by ObservedObserver** [Kanaries/Rath#381]
![image](https://github.com/Kanaries/Rath/assets/22167673/6e399c08-7445-446f-b3cf-dccb9195cdcc)
Issue Desc: vega-lite spec cannot render field whose title contains `\n`. RATH needs to check the name of fields and remove those illegal symbols.

Solution: after load data, remove "\n" in "name" in `fieldMetas`

**Comment by NasimFatima** [comment]
I am going to take this issue. Please assign this to me.

**Comment by ObservedObserver** [comment]
https://github.com/Kanaries/Rath/blob/66118bfdc4cc0eb6e5800b04762c15ef91bbb1cf/packages/rath-client/src/store/dataSourceStore.ts#L572

@NasimFatima Thanks!! Check the `loadDataWithInferMeta` method, it is used to load datasets and their meta info, which contains the field name we need to fix.
You can remove illegal symbols from names here.

**Comment by jojocys** [comment]
solved
