### ISSUE TITLE
使用反馈和建议(Feedback and Suggestions)

### ISSUE THREAD

**Issue by ObservedObserver** [Kanaries/Rath#45]
如果你使用Rath之后有什么反馈或者建议，可以发布在这里。不限任何内容，如未能完成完整的分析流程；找不到一些指引；可视化效果差；页面卡顿；网络资源加载慢等。

QQ交流群：129132269

You can write feedback or suggestions here after using Rath. (fail to finish an analysis pipeline; few instructions; bad visualization; bad performance; slow page loading etc )

**Comment by baiheinet** [comment]
一点小建议，当使用平均值的时候，应该有个平均基准线
![image](https://user-images.githubusercontent.com/900786/127415262-29b5a8fe-a083-4fe1-b939-8a72e47d0691.png)

**Comment by ObservedObserver** [comment]
> 一点小建议，当使用平均值的时候，应该有个平均基准线
> ![image](https://user-images.githubusercontent.com/900786/127415262-29b5a8fe-a083-4fe1-b939-8a72e47d0691.png)

关于辅助标注我也在考虑。主要难点是，探索模块的推荐是高维的，对于一些高维的复杂的模式，很难给出具有普适性的标注方法。但如果某一类标注很明显或很具体，是可以被具体的洞察识别算子检测到，这个我做过一个很简单的测试demo：[auto-anotation](https://github.com/ObservedObserver/auto-annotation)

**Comment by baiheinet** [comment]
我是直接用Rath的源码小小改造了一下，集成到系统的，本来我们的系统也是基于Umi的，只是把office-ui-fabric-react全部 Antd统一化了，Rath的源码以及目录结构都很清晰明了，值得关注与推荐，还有相应的[理论笔记](https://www.yuque.com/chenhao-sv93h/umv780)参考，真心用的舒心，♥

**Comment by baiheinet** [comment]
![image](https://user-images.githubusercontent.com/900786/128849742-31b020da-c09a-49bc-a33b-6fa807a64427.png)
看了微软的SandDance，是否考虑把Data cube 用三维显示 更能洞察数据

**Comment by ObservedObserver** [comment]
> ![image](https://camo.githubusercontent.com/697da1b23bb146ea3549e2268efab31cbfe434d992c26822161c3a551607fbb2/68747470733a2f2f7069632e696d6764622e636e2f6974656d2f3631313235353165353133323932336266383832643638382e676966)
> 看了微软的SandDance，是否考虑把Data cube 用三维显示 更能洞察数据

SandDance的核心可视化技术是unit visualization，这一点是非常值得参考的，它可以对不同可视化之间数据的关联做一个大致的展示。这一点在近期Rath完善图表联想和叙事可视化(多个图表讲一个故事)后，会考虑引入类似的机制。
另外一点是3D可视化的问题，这个其实Rath的推荐引擎是可以推荐出3D可视化的（有个配置，不过没有开放出来），只是目前Rath使用的图表库(vega-lite)是2D的，所以后续是可以提供3D可视化的。

顺便问一下，最近Rath正在做一个新的大版本，也想收集一些用户案例作为参考和后续社区宣传。不知道您有没有兴趣和我们分享你们的使用经验。

**Comment by baiheinet** [comment]
我们其实是施工行业，想往[数字孪生](https://developer.bentley.com/samples/)这个方向走一下，感觉Rath 是 OLAP 往 Graph Analysis走的一个中间状态，有很强的可操作性和工程性，也是在探索阶段，没有什么经验😳
